/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 1;
  /** RegularExpression Id. */
  int PLUSOP = 2;
  /** RegularExpression Id. */
  int MINUSOP = 3;
  /** RegularExpression Id. */
  int MULOP = 4;
  /** RegularExpression Id. */
  int DIVOP = 5;
  /** RegularExpression Id. */
  int REMAINOP = 6;
  /** RegularExpression Id. */
  int OPEN = 7;
  /** RegularExpression Id. */
  int CLOSE = 8;
  /** RegularExpression Id. */
  int EQOP = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
